---
Name: zauberfisch-page-builder
---
SilverStripe\Admin\LeftAndMain:
  extensions:
    - zauberfisch\PageBuilder\Extensions\LeftAndMainExtension
zauberfisch\PageBuilder\PageBuilderField:
  css:
    - "zauberfisch/silverstripe-page-builder: client/dist/styles/bundle.css"
  javascript:
    - "zauberfisch/silverstripe-page-builder: client/dist/js/vendor.js"
    - "zauberfisch/silverstripe-page-builder: client/dist/js/bundle.js"
  lang:
    - "zauberfisch/silverstripe-page-builder: client/lang"
